#!/bin/bash
function add_overrides
{
    # Borean Tundra - Taken by the Scourge - Give all members of a group credit
    sed -i '48s|.*$|#include \"Group.h\"\n|' $CORE_DIRECTORY/src/server/scripts/Northrend/zone_borean_tundra.cpp
    sed -i '349,362d' $CORE_DIRECTORY/src/server/scripts/Northrend/zone_borean_tundra.cpp
    sed -i '348s|.*$|            Player* player = killer->ToPlayer();\n            uint8 uiRand = urand(0, 99);\n\n            if (uiRand < 40)\n            {\n                if (Group* group = player->GetGroup())\n                {\n                    for (GroupReference* groupRef = group->GetFirstMember(); groupRef != nullptr; groupRef = groupRef->next())\n                    {\n                        if (Player* member = groupRef->GetSource())\n                        {\n                            if (member->IsInMap(player) \&\& member->GetQuestStatus(QUEST_TAKEN_BY_THE_SCOURGE) == QUEST_STATUS_INCOMPLETE)\n                            {\n                                member->CastSpell(me, SPELL_FREED_WARSONG_PEON, true);\n                                member->KilledMonsterCredit(NPC_WARSONG_PEON);\n                            }\n                        }\n                    }\n                }\n                else\n                {\n                    player->CastSpell(me, SPELL_FREED_WARSONG_PEON, true);\n                    player->KilledMonsterCredit(NPC_WARSONG_PEON);\n                }\n            }\n            else if (uiRand < 80)\n            {\n                player->CastSpell(me, nerubarVictims[urand(0, 2)], true);\n            }|' $CORE_DIRECTORY/src/server/scripts/Northrend/zone_borean_tundra.cpp

    # Dragonblight - Torture the Torturer - Give all members of a group credit
    sed -i '40s|.*$|#include \"Group.h\"\n|' $CORE_DIRECTORY/src/server/scripts/Northrend/zone_dragonblight.cpp
    sed -i '1914s|.*$|                {\n                    if (Group* group = player->GetGroup())\n                    {\n                        for (GroupReference* groupRef = group->GetFirstMember(); groupRef != nullptr; groupRef = groupRef->next())\n                        {\n                            if (Player* member = groupRef->GetSource())\n                            {\n                                if (member->IsInMap(player))\n                                {\n                                    member->KilledMonsterCredit(NPC_TORTURER_LECRAFT);\n                                }\n                            }\n                        }\n                    }\n                    else\n                    {\n                        player->KilledMonsterCredit(NPC_TORTURER_LECRAFT);\n                    }\n                }|' $CORE_DIRECTORY/src/server/scripts/Northrend/zone_dragonblight.cpp
}
