DROP TABLE IF EXISTS `realm_settings`;
CREATE TABLE `realm_settings` (
	`id` INT(10) NOT NULL DEFAULT '-1',
	`node` INT(10) NOT NULL DEFAULT '-1',
	`setting` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	`value` TEXT NOT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`id`, `node`, `setting`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;

INSERT INTO `realm_settings` (`id`, `node`, `setting`, `value`) VALUES
(-1, -1, 'build.auth', 'true'),
(-1, -1, 'build.world', 'true'),
(-1, -1, 'database.auth', 'acore_auth'),
(-1, -1, 'database.characters', 'acore_characters'),
(-1, -1, 'database.playerbots', 'acore_playerbots'),
(-1, -1, 'database.world', 'acore_world'),
(-1, -1, 'git.branch', 'master'),
(-1, -1, 'git.repository', 'azerothcore/azerothcore-wotlk'),
(-1, -1, 'module.ah_bot', 'false'),
(-1, -1, 'module.ah_bot.account', '1'),
(-1, -1, 'module.ah_bot.buy_items', 'false'),
(-1, -1, 'module.ah_bot.character', '1'),
(-1, -1, 'module.ah_bot.items', '250'),
(-1, -1, 'module.ah_bot.items_per_cycle', '200'),
(-1, -1, 'module.ah_bot.max_item_level', '0'),
(-1, -1, 'module.ah_bot.sell_items', 'false'),
(-1, -1, 'module.ah_bot.use_buyprice', 'false'),
(-1, -1, 'module.appreciation', 'false'),
(-1, -1, 'module.appreciation.level_boost', 'true'),
(-1, -1, 'module.appreciation.level_boost.included_copper', '2500000'),
(-1, -1, 'module.appreciation.level_boost.level', '60'),
(-1, -1, 'module.appreciation.require_certificate', 'true'),
(-1, -1, 'module.appreciation.reward_at_max_level', 'false'),
(-1, -1, 'module.appreciation.unlock_continents', 'true'),
(-1, -1, 'module.assistant', 'false'),
(-1, -1, 'module.assistant.fp.tbc', 'true'),
(-1, -1, 'module.assistant.fp.tbc.cost', '1000000'),
(-1, -1, 'module.assistant.fp.tbc.required_level', '70'),
(-1, -1, 'module.assistant.fp.vanilla', 'true'),
(-1, -1, 'module.assistant.fp.vanilla.cost', '250000'),
(-1, -1, 'module.assistant.fp.vanilla.required_level', '60'),
(-1, -1, 'module.assistant.fp.wotlk', 'false'),
(-1, -1, 'module.assistant.fp.wotlk.cost', '2500000'),
(-1, -1, 'module.assistant.fp.wotlk.required_level', '80'),
(-1, -1, 'module.assistant.professions.apprentice', 'true'),
(-1, -1, 'module.assistant.professions.apprentice.cost', '1000000'),
(-1, -1, 'module.assistant.professions.artisan', 'true'),
(-1, -1, 'module.assistant.professions.artisan.cost', '7500000'),
(-1, -1, 'module.assistant.professions.expert', 'true'),
(-1, -1, 'module.assistant.professions.expert.cost', '5000000'),
(-1, -1, 'module.assistant.professions.grand_master', 'false'),
(-1, -1, 'module.assistant.professions.grand_master.cost', '25000000'),
(-1, -1, 'module.assistant.professions.journeyman', 'true'),
(-1, -1, 'module.assistant.professions.journeyman.cost', '2500000'),
(-1, -1, 'module.assistant.professions.master', 'false'),
(-1, -1, 'module.assistant.professions.master.cost', '12500000'),
(-1, -1, 'module.assistant.utilities', 'true'),
(-1, -1, 'module.assistant.vendor.containers', 'true'),
(-1, -1, 'module.assistant.vendor.gems', 'true'),
(-1, -1, 'module.assistant.vendor.glyphs', 'true'),
(-1, -1, 'module.assistant.vendor.heirlooms', 'true'),
(-1, -1, 'module.groupquests', 'false'),
(-1, -1, 'module.junktogold', 'false'),
(-1, -1, 'module.learnspells', 'false'),
(-1, -1, 'module.learnspells.class_spells', 'true'),
(-1, -1, 'module.learnspells.proficiencies', 'true'),
(-1, -1, 'module.learnspells.quest_spells', 'true'),
(-1, -1, 'module.learnspells.riding.apprentice', 'false'),
(-1, -1, 'module.learnspells.riding.artisan', 'false'),
(-1, -1, 'module.learnspells.riding.cold_weather_flying', 'false'),
(-1, -1, 'module.learnspells.riding.expert', 'false'),
(-1, -1, 'module.learnspells.riding.journeyman', 'false'),
(-1, -1, 'module.learnspells.talent_ranks', 'true'),
(-1, -1, 'module.playerbots', 'false'),
(-1, -1, 'module.playerbots.accounts', '200'),
(-1, -1, 'module.playerbots.bots', '50'),
(-1, -1, 'module.playerbots.random_level', 'true'),
(-1, -1, 'module.playerbots.start_level', '5'),
(-1, -1, 'module.progression', 'false'),
(-1, -1, 'module.progression.aura', '4'),
(-1, -1, 'module.progression.enforce.dungeonfinder', 'true'),
(-1, -1, 'module.progression.enforce.questinfo', 'true'),
(-1, -1, 'module.progression.enforce.dualtalent', 'true'),
(-1, -1, 'module.progression.patch', '21'),
(-1, -1, 'module.progression.reset', 'false'),
(-1, -1, 'module.recruitafriend', 'false'),
(-1, -1, 'module.recruitafriend.account_age', '7'),
(-1, -1, 'module.recruitafriend.celestial_steed', 'true'),
(-1, -1, 'module.recruitafriend.duration', '90'),
(-1, -1, 'module.recruitafriend.reward_days', '30'),
(-1, -1, 'module.recruitafriend.swift_zhevra', 'true'),
(-1, -1, 'module.recruitafriend.touring_rocket', 'true'),
(-1, -1, 'module.skip_dk_starting_area', 'false'),
(-1, -1, 'module.weekendbonus', 'false'),
(-1, -1, 'module.weekendbonus.multiplier.experience', '2.0'),
(-1, -1, 'module.weekendbonus.multiplier.money', '2.0'),
(-1, -1, 'module.weekendbonus.multiplier.professions', '2'),
(-1, -1, 'module.weekendbonus.multiplier.proficiencies', '2'),
(-1, -1, 'module.weekendbonus.multiplier.reputation', '2.0'),
(-1, -1, 'telegram.chat_id', '0'),
(-1, -1, 'telegram.token', '0'),
(-1, -1, 'world.address', '127.0.0.1'),
(-1, -1, 'world.cluster', 'false'),
(-1, -1, 'world.cluster.auth_address', '127.0.0.1'),
(-1, -1, 'world.cluster.maps', 'all'),
(-1, -1, 'world.cluster.node_address', '127.0.0.1'),
(-1, -1, 'world.data_directory', '.'),
(-1, -1, 'world.expansion', '2'),
(-1, -1, 'world.leave_group_on_logout', 'true'),
(-1, -1, 'world.motd', 'Welcome to an AzerothCore server.'),
(-1, -1, 'world.name', 'AzerothCore'),
(-1, -1, 'world.player_limit', '1000'),
(-1, -1, 'world.port', '8085'),
(-1, -1, 'world.preload_grids', 'false'),
(-1, -1, 'world.quest_in_raid', 'false'),
(-1, -1, 'world.raid_min_level', '10'),
(-1, -1, 'world.rate.experience', '1'),
(-1, -1, 'world.rate.money', '1'),
(-1, -1, 'world.rate.reputation', '1'),
(-1, -1, 'world.realm_zone', '1'),
(-1, -1, 'world.set_creatures_active', 'false'),
(-1, -1, 'world.type', '0'),
(-1, -1, 'world.warden', 'true');
