DROP TABLE IF EXISTS `realm_settings`;
CREATE TABLE `realm_settings` (
	`id` INT(10) NOT NULL DEFAULT '-1',
	`node` INT(10) NOT NULL DEFAULT '-1',
	`setting` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	`value` TEXT NOT NULL COLLATE 'utf8mb4_general_ci',
	`comment` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`id`, `node`, `setting`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;

INSERT INTO `realm_settings` (`id`, `node`, `setting`, `value`, `comment`) VALUES
(-1, -1, 'build.auth', 'true', 'Build auth server'),
(-1, -1, 'build.world', 'true', 'Build world server'),
(-1, -1, 'database.auth', 'acore_auth', 'Name of the auth database'),
(-1, -1, 'database.characters', 'acore_characters', 'Name of the characters database'),
(-1, -1, 'database.playerbots', 'acore_playerbots', 'Name of the playerbots database'),
(-1, -1, 'database.world', 'acore_world', 'Name of the world database'),
(-1, -1, 'git.branch', 'master', 'The branch of set repository to use'),
(-1, -1, 'git.repository', 'azerothcore/azerothcore-wotlk', 'The repository to use'),
(-1, -1, 'module.ah_bot', 'false', 'Enable the auction house bot module'),
(-1, -1, 'module.ah_bot.account', '1', 'Account id of the bot'),
(-1, -1, 'module.ah_bot.buy_items', 'false', 'The bot will buy items'),
(-1, -1, 'module.ah_bot.character', '1', 'Character guid for the bot'),
(-1, -1, 'module.ah_bot.items', '250', 'The number of items the bot will post to each auction house'),
(-1, -1, 'module.ah_bot.items_per_cycle', '200', 'Number of items to post per cycle'),
(-1, -1, 'module.ah_bot.max_item_level', '0', 'The max item level of items the bot will post'),
(-1, -1, 'module.ah_bot.sell_items', 'false', 'The bot will sell items'),
(-1, -1, 'module.ah_bot.use_buyprice', 'false', 'Use buy price instead of sell price'),
(-1, -1, 'module.appreciation', 'false', 'Enable the appreciation module'),
(-1, -1, 'module.appreciation.level_boost', 'true', 'Allow being boosted to a specific level and be given a basic set of equipment'),
(-1, -1, 'module.appreciation.level_boost.included_copper', '2500000', 'The amount of copper to give the player when using the level boost feature'),
(-1, -1, 'module.appreciation.level_boost.level', '60', 'The level to give the player when using the level boost feature'),
(-1, -1, 'module.appreciation.require_certificate', 'true', 'Require certificates to use these feature'),
(-1, -1, 'module.appreciation.reward_at_max_level', 'false', 'Give the player a certificate of appreciation when reaching max level'),
(-1, -1, 'module.appreciation.unlock_continents', 'true', 'Allow unlocking flight paths for all continents'),
(-1, -1, 'module.assistant', 'false', 'Enable the assistant module'),
(-1, -1, 'module.assistant.fp.tbc', 'true', 'Allow players to unlock flight paths in Outland'),
(-1, -1, 'module.assistant.fp.tbc.cost', '1000000', 'The cost in copper to unlock flight paths in Outland'),
(-1, -1, 'module.assistant.fp.tbc.required_level', '70', 'The required level to unlock flight paths in Outland'),
(-1, -1, 'module.assistant.fp.vanilla', 'true', 'Allow players to unlock flight paths in Eastern Kingdoms and Kalimdor'),
(-1, -1, 'module.assistant.fp.vanilla.cost', '250000', 'The cost in copper to unlock flight paths in Eastern Kingdoms and Kalimdor'),
(-1, -1, 'module.assistant.fp.vanilla.required_level', '60', 'The required level to unlock flight paths in Eastern Kingdoms and Kalimdor'),
(-1, -1, 'module.assistant.fp.wotlk', 'false', 'Allow players to unlock flight paths in Northrend'),
(-1, -1, 'module.assistant.fp.wotlk.cost', '2500000', 'The cost in copper to unlock flight paths in Northrend'),
(-1, -1, 'module.assistant.fp.wotlk.required_level', '80', 'The required level to unlock flight paths in Northrend'),
(-1, -1, 'module.assistant.professions.apprentice', 'true', 'Allow players to level up professions to 75 via the assistant'),
(-1, -1, 'module.assistant.professions.apprentice.cost', '1000000', 'The cost to level up professions to 75'),
(-1, -1, 'module.assistant.professions.artisan', 'true', 'Allow players to level up professions to 300 via the assistant'),
(-1, -1, 'module.assistant.professions.artisan.cost', '7500000', 'The cost to level up professions to 75'),
(-1, -1, 'module.assistant.professions.expert', 'true', 'Allow players to level up professions to 225 via the assistant'),
(-1, -1, 'module.assistant.professions.expert.cost', '5000000', 'The cost to level up professions to 75'),
(-1, -1, 'module.assistant.professions.grand_master', 'false', 'Allow players to level up professions to 450 via the assistant'),
(-1, -1, 'module.assistant.professions.grand_master.cost', '25000000', 'The cost to level up professions to 75'),
(-1, -1, 'module.assistant.professions.journeyman', 'true', 'Allow players to level up professions to 150 via the assistant'),
(-1, -1, 'module.assistant.professions.journeyman.cost', '2500000', 'The cost to level up professions to 75'),
(-1, -1, 'module.assistant.professions.master', 'false', 'Allow players to level up professions to 375 via the assistant'),
(-1, -1, 'module.assistant.professions.master.cost', '12500000', 'The cost to level up professions to 75'),
(-1, -1, 'module.assistant.utilities', 'true', 'Allow players to activate various services from the assistant'),
(-1, -1, 'module.assistant.vendor.containers', 'true', 'Allow players to obtain bags from the assistant'),
(-1, -1, 'module.assistant.vendor.gems', 'true', 'Allow players to obtain gems from the assistant'),
(-1, -1, 'module.assistant.vendor.glyphs', 'true', 'Allow players to obtain glyphs from the assistant'),
(-1, -1, 'module.assistant.vendor.heirlooms', 'true', 'Allow players to obtain heirlooms from the assistant'),
(-1, -1, 'module.groupquests', 'false', 'Enable the group quests module'),
(-1, -1, 'module.junktogold', 'false', 'Enable the junk to gold module'),
(-1, -1, 'module.learnspells', 'false', 'Enable the learn spells module'),
(-1, -1, 'module.learnspells.class_spells', 'true', 'Teach players spells specific to their class'),
(-1, -1, 'module.learnspells.proficiencies', 'true', 'Teach players proficiencies specific to their class'),
(-1, -1, 'module.learnspells.quest_spells', 'true', 'Teach players spells normally obtained via quests'),
(-1, -1, 'module.learnspells.riding.apprentice', 'false', 'Teach players apprentice riding and mounts'),
(-1, -1, 'module.learnspells.riding.artisan', 'false', 'Teach players artisan riding and mounts'),
(-1, -1, 'module.learnspells.riding.cold_weather_flying', 'false', 'Teach players Cold Weather Flying (at level 77)'),
(-1, -1, 'module.learnspells.riding.expert', 'false', 'Teach players expert riding and mounts'),
(-1, -1, 'module.learnspells.riding.journeyman', 'false', 'Teach players journeyman riding and mounts'),
(-1, -1, 'module.learnspells.talent_ranks', 'true', 'Teach players talent ranks of talents they have'),
(-1, -1, 'module.playerbots', 'false', 'Enable the playerbots module'),
(-1, -1, 'module.playerbots.accounts', '200', 'The number of random bot accounts to create'),
(-1, -1, 'module.playerbots.bots', '50', 'The number of random bots to spawn in the world'),
(-1, -1, 'module.playerbots.random_level', 'true', 'Enable bots to spawn at and change to random levels'),
(-1, -1, 'module.playerbots.start_level', '5', 'The level the bots will start at if random level is disabled'),
(-1, -1, 'module.progression', 'false', 'Enable the progression module'),
(-1, -1, 'module.progression.aura', '4', 'The aura inside Icecrown Citadel based on the set patch'),
(-1, -1, 'module.progression.enforce.dungeonfinder', 'true', 'Enforce the availability of the dungeon finder'),
(-1, -1, 'module.progression.enforce.questinfo', 'true', 'Enforce quest-related information'),
(-1, -1, 'module.progression.patch', '4', 'The patch to use for progression'),
(-1, -1, 'module.progression.reset', 'false', 'Reapply all SQL files on startup'),
(-1, -1, 'module.recruitafriend', 'false', 'Enable the recruit-a-friend module'),
(-1, -1, 'module.recruitafriend.account_age', '7', 'The amount of days since the account was created where it can still be recruited'),
(-1, -1, 'module.recruitafriend.celestial_steed', 'true', 'Give the player the Celestial Steed mount'),
(-1, -1, 'module.recruitafriend.duration', '90', 'The amount of days that a referral will stay active'),
(-1, -1, 'module.recruitafriend.reward_days', '30', 'This defines the amount of days since the referral that is required before the accounts receive special rewards'),
(-1, -1, 'module.recruitafriend.swift_zhevra', 'true', 'Give the player the Swift Zhevra mount'),
(-1, -1, 'module.recruitafriend.touring_rocket', 'true', 'Give the player the X-53 Touring Rocket mount'),
(-1, -1, 'module.skip_dk_starting_area', 'false', 'Enable the skip dk starting area module'),
(-1, -1, 'module.weekendbonus', 'false', 'Enable the weekend bonus module'),
(-1, -1, 'module.weekendbonus.multiplier.experience', '2.0', 'The multiplier for experience rate during weekends'),
(-1, -1, 'module.weekendbonus.multiplier.money', '2.0', 'The multiplier for money rate during weekends'),
(-1, -1, 'module.weekendbonus.multiplier.professions', '2', 'The multiplier for profession skill up rate during weekends'),
(-1, -1, 'module.weekendbonus.multiplier.proficiencies', '2', 'The multiplier for proficiencies rate during weekends'),
(-1, -1, 'module.weekendbonus.multiplier.reputation', '2.0', 'The multiplier for reputation rate during weekends'),
(-1, -1, 'telegram.chat_id', '0', 'Telegram chat id. Used to send messages if errors occur'),
(-1, -1, 'telegram.token', '0', 'Telegram token. Used to send messages if errors occur'),
(-1, -1, 'world.address', '127.0.0.1', 'The address used to connect to the world server'),
(-1, -1, 'world.cluster', 'false', 'Enable clustering'),
(-1, -1, 'world.cluster.auth_address', '127.0.0.1', 'Address of the auth server'),
(-1, -1, 'world.cluster.maps', 'all', 'The maps enabled for the node'),
(-1, -1, 'world.cluster.node_address', '127.0.0.1', 'Address of the node'),
(-1, -1, 'world.data_version', '0', 'The installed client data version'),
(-1, -1, 'world.expansion', '2', 'The active expansion'),
(-1, -1, 'world.leave_group_on_logout', 'true', 'Leave group when logging out'),
(-1, -1, 'world.motd', 'Welcome to an AzerothCore server.', 'Message of the day'),
(-1, -1, 'world.name', 'AzerothCore', 'Name of the realm as shown in the realm selection screen'),
(-1, -1, 'world.player_limit', '1000', 'Maximum number of players in the world'),
(-1, -1, 'world.port', '8085', 'The port used by the world server'),
(-1, -1, 'world.preload_grids', 'false', 'Preload all grids on all non-instanced maps'),
(-1, -1, 'world.quest_in_raid', 'false', 'Allow non-raid quests to be completed while in a raid group'),
(-1, -1, 'world.raid_min_level', '10', 'The minimum level required to join a raid group'),
(-1, -1, 'world.rate.experience', '1', 'Multiplier of all experience rates outside battlegrounds'),
(-1, -1, 'world.rate.money', '1', 'Multiplier for money looted'),
(-1, -1, 'world.rate.reputation', '1', 'Multiplier for reputation gained'),
(-1, -1, 'world.realm_zone', '1', 'Set allowed alphabet in character names etc'),
(-1, -1, 'world.set_creatures_active', 'false', 'Set all creatures with waypoints active'),
(-1, -1, 'world.type', '0', 'Realm type'),
(-1, -1, 'world.warden', 'true', 'Enable Warden anti-cheat system');
