EVENT_ON_LOGIN             = 3
EVENT_ON_GIVE_XP           = 12
EVENT_ON_LEVEL_CHANGED     = 13
EVENT_ON_REPUTATION_CHANGE = 15
EVENT_ON_FIRST_LOGIN       = 30
EVENT_ON_LOOT_MONEY        = 37
EVENT_ON_COMMAND           = 42
