GOSSIP_ICON_CHAT               = 0 -- white chat bubble
GOSSIP_ICON_VENDOR             = 1 -- brown bag
GOSSIP_ICON_TAXI               = 2 -- flightmarker (paperplane)
GOSSIP_ICON_TRAINER            = 3 -- brown book (trainer)
GOSSIP_ICON_INTERACT_1         = 4 -- golden interaction wheel
GOSSIP_ICON_MONEY_BAG          = 6 -- brown bag (with gold coin in lower corner)
GOSSIP_ICON_TALK               = 7 -- white chat bubble (with "..." inside)
GOSSIP_ICON_TABARD             = 8 -- white tabard
GOSSIP_ICON_BATTLE             = 9 -- two crossed swords
GOSSIP_ICON_DOT                = 10 -- yellow dot/point
